export const articleContants = {
    CREATE_REQUEST: "ARTICLE_CREATE_REQUEST",
    CREATE_SUCCESS: "ARTICLE_CREATE_REQUEST",
    CREATE_ERROR: "ARTICLE_CREATE_ERROR",
    UPDATE_REQUEST: "ARTICLE_UPDATE_REQUEST",
    UPDATE_SUCCESS: "ARTICLE_UPDATE_REQUEST",
    UPDATE_ERROR: "ARTICLE_UPDATE_ERROR",
    GET_REQUEST: "ARTICLE_GET_REQUEST",
    GET_SUCCESS: "ARTICLE_GET_REQUEST",
    GET_ERROR: "ARTICLE_GET_ERROR",
    DELETE_REQUEST: "ARTICLE_DELETE_REQUEST",
    DELETE_SUCCESS: "ARTICLE_DELETE_REQUEST",
    DELETE_ERROR: "ARTICLE_DELETE_ERROR",
}